In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
file_path = 'normalised_data.csv'

In [3]:
data = pd.read_csv(file_path)
data.head()

,Overall Rank,School,State,Undergrad. Enrollment,Admission Rate,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Non-Need-Based Aid+,Average Debt,Cost Rank,SAT,ACT
0,1,California Institute of Technology,CA,0.044895,0.109375,0.000000,0.797753,0.629630,10,0.764995,0.233873,1.0000,0.904110,0.354043,0.141414,0.363044,4,0.980392,1.000000
1,2,Rice University,TX,0.140040,0.156250,0.142857,0.764045,0.777778,19,0.630298,0.398303,1.0000,0.835616,0.484688,0.333333,0.450260,5,0.784314,0.822222
2,4,Swarthmore College,PA,0.072697,0.156250,0.357143,0.966292,0.888889,4,0.951370,0.511170,1.0000,0.794521,0.112392,0.010101,0.452174,21,0.882353,0.955556
3,6,Webb Institute,NY,0.000000,0.437500,0.285714,0.887640,0.555556,39,0.000000,0.000000,0.0000,1.000000,0.000000,1.000000,0.202006,1,1.000000,1.000000
4,8,Washington and Lee University,VA,0.086650,0.265625,0.571429,0.966292,0.777778,30,0.688598,0.427440,0.9875,0.821918,0.472688,0.303030,0.554063,9,0.784314,0.755556

In [4]:
final_data = data.copy()

In [5]:
final_data = final_data[['6-year Grad. Rate', '4-year Grad. Rate', 'SAT', 'ACT']]

In [6]:
final_data.head()

   6-year Grad. Rate  4-year Grad. Rate       SAT       ACT
0           0.629630           0.797753  0.980392  1.000000
1           0.777778           0.764045  0.784314  0.822222
2           0.888889           0.966292  0.882353  0.955556
3           0.555556           0.887640  1.000000  1.000000
4           0.777778           0.966292  0.784314  0.755556

In [7]:
values = []
sat_val = final_data['SAT']
for s in final_data['SAT']:
    if s > 0.8:
        values.append('A')
    elif s > 0.6 and s < 0.8:
        values.append('B')
    else:
        values.append('C')
final_data['SAT_val'] = values
(final_data.head())

   6-year Grad. Rate  4-year Grad. Rate       SAT       ACT SAT_val
0           0.629630           0.797753  0.980392  1.000000       A
1           0.777778           0.764045  0.784314  0.822222       B
2           0.888889           0.966292  0.882353  0.955556       A
3           0.555556           0.887640  1.000000  1.000000       A
4           0.777778           0.966292  0.784314  0.755556       B

In [8]:
values = []
act_val = final_data['ACT']
for s in final_data['ACT']:
    if s > 0.8:
        values.append('D')
    elif s > 0.6 and s < 0.8:
        values.append('E')
    else:
        values.append('F')
final_data['ACT_val'] = values
(final_data.head())

   6-year Grad. Rate  4-year Grad. Rate       SAT       ACT SAT_val ACT_val
0           0.629630           0.797753  0.980392  1.000000       A       D
1           0.777778           0.764045  0.784314  0.822222       B       D
2           0.888889           0.966292  0.882353  0.955556       A       D
3           0.555556           0.887640  1.000000  1.000000       A       D
4           0.777778           0.966292  0.784314  0.755556       B       E

In [9]:
values = []
year_4_grad_rate_val = final_data['4-year Grad. Rate']
for s in final_data['4-year Grad. Rate']:
    if s > 0.8:
        values.append('G')
    elif s > 0.6 and s < 0.8:
        values.append('H')
    else:
        values.append('I')
final_data['year_4_grad_rate_val'] = values
(final_data.head())

,6-year Grad. Rate,4-year Grad. Rate,SAT,ACT,SAT_val,ACT_val,year_4_grad_rate_val
0,0.629630,0.797753,0.980392,1.000000,A,D,H
1,0.777778,0.764045,0.784314,0.822222,B,D,H
2,0.888889,0.966292,0.882353,0.955556,A,D,G
3,0.555556,0.887640,1.000000,1.000000,A,D,G
4,0.777778,0.966292,0.784314,0.755556,B,E,G

In [10]:
values = []
year_6_grad_rate_val = final_data['6-year Grad. Rate']
for s in final_data['6-year Grad. Rate']:
    if s > 0.8:
        values.append('J')
    elif s > 0.6 and s < 0.8:
        values.append('K')
    else:
        values.append('L')
final_data['year_6_grad_rate_val'] = values
(final_data.head())

,6-year Grad. Rate,4-year Grad. Rate,SAT,ACT,SAT_val,ACT_val,year_4_grad_rate_val,year_6_grad_rate_val
0,0.629630,0.797753,0.980392,1.000000,A,D,H,K
1,0.777778,0.764045,0.784314,0.822222,B,D,H,K
2,0.888889,0.966292,0.882353,0.955556,A,D,G,J
3,0.555556,0.887640,1.000000,1.000000,A,D,G,L
4,0.777778,0.966292,0.784314,0.755556,B,E,G,K

In [11]:
#final_data = final_data[['6-year Grad. Rate', '4-year Grad. Rate', 'SAT', 'ACT']]
final_data = final_data[['year_6_grad_rate_val', 'year_4_grad_rate_val', 'SAT_val', 'ACT_val']]

In [12]:
list_of_vals = final_data.values.tolist()
print(list_of_vals)

[['K', 'H', 'A', 'D'], ['K', 'H', 'B', 'D'], ['J', 'G', 'A', 'D'], ['L', 'G', 'A', 'D'], ['K', 'G', 'B', 'E'], ['K', 'G', 'B', 'D'], ['J', 'G', 'A', 'D'], ['J', 'G', 'B', 'E'], ['J', 'G', 'B', 'D'], ['J', 'G', 'B', 'D'], ['K', 'G', 'B', 'D'], ['L', 'H', 'B', 'E'], ['K', 'G', 'A', 'D'], ['K', 'G', 'B', 'D'], ['J', 'G', 'B', 'F'], ['L', 'G', 'C', 'F'], ['L', 'G', 'C', 'E'], ['K', 'G', 'B', 'E'], ['L', 'G', 'C', 'F'], ['L', 'G', 'B', 'E'], ['L', 'G', 'B', 'F'], ['L', 'H', 'B', 'E'], ['L', 'G', 'B', 'E'], ['K', 'G', 'B', 'E'], ['J', 'G', 'C', 'F'], ['L', 'G', 'A', 'D'], ['K', 'G', 'C', 'E'], ['L', 'H', 'B', 'E'], ['K', 'G', 'B', 'E'], ['L', 'H', 'B', 'F'], ['L', 'G', 'B', 'F'], ['L', 'G', 'C', 'F'], ['L', 'H', 'C', 'E'], ['L', 'G', 'C', 'F'], ['L', 'G', 'C', 'F'], ['L', 'G', 'C', 'F'], ['L', 'G', 'C', 'F'], ['L', 'I', 'C', 'F'], ['L', 'G', 'C', 'F'], ['L', 'H', 'C', 'F'], ['L', 'G', 'B', 'E'], ['L', 'H', 'B', 'F'], ['L', 'H', 'B', 'F'], ['L', 'G', 'C', 'F'], ['L', 'H', 'C', 'D'], ['L', 'I', 'C', 'E'], ['L', 'G', 'C', 'F'], ['K', 'I', 'C', 'E'], ['L', 'H', 'B', 'F'], ['L', 'H', 'C', 'E'], ['L', 'H', 'B', 'E'], ['L', 'G', 'C', 'F'], ['L', 'H', 'C', 'F'], ['L', 'H', 'C', 'F'], ['L', 'H', 'A', 'F'], ['L', 'G', 'C', 'F'], ['K', 'I', 'C', 'F'], ['L', 'I', 'C', 'D'], ['L', 'H', 'C', 'F']]

In [13]:
import pprint

def load_dataset():
    """Loads an example of market basket transactions for testing purposes.

    Returns
    -------
    A list (database) of lists (transactions). Each element of a transaction 
    is an item.
    """
    return list_of_vals

dataset = load_dataset() # list of transactions; each transaction is a list of items
D = list(map(set, dataset)) # set of transactions; each transaction is a list of items
print(len(dataset))
pprint.pprint(dataset)

59
[['K', 'H', 'A', 'D'],
 ['K', 'H', 'B', 'D'],
 ['J', 'G', 'A', 'D'],
 ['L', 'G', 'A', 'D'],
 ['K', 'G', 'B', 'E'],
 ['K', 'G', 'B', 'D'],
 ['J', 'G', 'A', 'D'],
 ['J', 'G', 'B', 'E'],
 ['J', 'G', 'B', 'D'],
 ['J', 'G', 'B', 'D'],
 ['K', 'G', 'B', 'D'],
 ['L', 'H', 'B', 'E'],
 ['K', 'G', 'A', 'D'],
 ['K', 'G', 'B', 'D'],
 ['J', 'G', 'B', 'F'],
 ['L', 'G', 'C', 'F'],
 ['L', 'G', 'C', 'E'],
 ['K', 'G', 'B', 'E'],
 ['L', 'G', 'C', 'F'],
 ['L', 'G', 'B', 'E'],
 ['L', 'G', 'B', 'F'],
 ['L', 'H', 'B', 'E'],
 ['L', 'G', 'B', 'E'],
 ['K', 'G', 'B', 'E'],
 ['J', 'G', 'C', 'F'],
 ['L', 'G', 'A', 'D'],
 ['K', 'G', 'C', 'E'],
 ['L', 'H', 'B', 'E'],
 ['K', 'G', 'B', 'E'],
 ['L', 'H', 'B', 'F'],
 ['L', 'G', 'B', 'F'],
 ['L', 'G', 'C', 'F'],
 ['L', 'H', 'C', 'E'],
 ['L', 'G', 'C', 'F'],
 ['L', 'G', 'C', 'F'],
 ['L', 'G', 'C', 'F'],
 ['L', 'G', 'C', 'F'],
 ['L', 'I', 'C', 'F'],
 ['L', 'G', 'C', 'F'],
 ['L', 'H', 'C', 'F'],
 ['L', 'G', 'B', 'E'],
 ['L', 'H', 'B', 'F'],
 ['L', 'H', 'B', 'F'],
 ['L', 'G', 'C', 'F'],
 ['L', 'H', 'C', 'D'],
 ['L', 'I', 'C', 'E'],
 ['L', 'G', 'C', 'F'],
 ['K', 'I', 'C', 'E'],
 ['L', 'H', 'B', 'F'],
 ['L', 'H', 'C', 'E'],
 ['L', 'H', 'B', 'E'],
 ['L', 'G', 'C', 'F'],
 ['L', 'H', 'C', 'F'],
 ['L', 'H', 'C', 'F'],
 ['L', 'H', 'A', 'F'],
 ['L', 'G', 'C', 'F'],
 ['K', 'I', 'C', 'F'],
 ['L', 'I', 'C', 'D'],
 ['L', 'H', 'C', 'F']]

In [14]:
def create_candidates(dataset, VERBOSE=False):
    """Creates a list of candidate 1-itemsets from a list of transactions.

    Parameters
    ----------
    dataset : list
        The dataset (a list of transactions) from which to generate candidate 
        itemsets.

    Returns
    -------
    The list of candidate itemsets (c1) passed as a frozenset (a set that is 
    immutable and hashable).
    """
    c1 = [] # list of all items in the database of transactions
    for transaction in dataset:
        for item in transaction:
            if not [item] in c1:
                c1.append([item])
    c1.sort()

    if VERBOSE:
        # Print a list of all the candidate items.
        print ("" \
            + "{" \
            + "".join(str(i[0]) + ", " for i in iter(c1)).rstrip(', ') \
            + "}")

    # Map c1 to a frozenset because it will be the key of a dictionary.
    return list(map(frozenset, c1))

In [15]:
# Generate candidate itemsets.
C1 = create_candidates(dataset, VERBOSE=True) # candidate 1-itemsets

{A, B, C, D, E, F, G, H, I, J, K, L}

In [16]:
def support_prune(dataset, candidates, min_support, VERBOSE=False):
    """Returns all candidate itemsets that meet a minimum support threshold.

    By the apriori principle, if an itemset is frequent, then all of its 
    subsets must also be frequent. As a result, we can perform support-based 
    pruning to systematically control the exponential growth of candidate 
    itemsets. Thus, itemsets that do not meet the minimum support level are 
    pruned from the input list of itemsets (dataset).

    Parameters
    ----------
    dataset : list
        The dataset (a list of transactions) from which to generate candidate 
        itemsets.

    candidates : frozenset
        The list of candidate itemsets.

    min_support : float
        The minimum support threshold.

    Returns
    -------
    retlist : list
        The list of frequent itemsets.

    support_data : dict
        The support data for all candidate itemsets.
    """
    sscnt = {} # set for support counts
    num_items=0
    for tid in dataset:
        num_items+=1
        for candidate in candidates:
            if candidate.issubset(tid):
                sscnt.setdefault(candidate, 0)
                sscnt[candidate] += 1

    #num_items = 5 #len(dataset) # total number of transactions in the dataset
    retlist = [] # array for unpruned itemsets
    support_data = {} # set for support data for corresponding itemsets
    for key in sscnt:
        # Calculate the support of itemset key.
        support = sscnt[key] / num_items
        if support >= min_support:
            retlist.insert(0, key)
        support_data[key] = support

    # Print a list of the pruned itemsets.
    if VERBOSE:
        for kset in retlist:
            for item in kset:
                print ("{" + str(item) + "}")
        #print
        for key in sscnt:
            print ("" \
                + "{" \
                + "".join([str(i) + ", " for i in iter(key)]).rstrip(', ') \
                + "}" \
                + ":  sup = " + str(support_data[key]))

    return retlist, support_data

In [17]:
# Prune candidate 1-itemsets via support-based pruning to generate frequent 1-itemsets.
F1, support_data = support_prune(D, C1, 0.8, VERBOSE=True)

{A}:  sup = 0.11864406779661017
{D}:  sup = 0.23728813559322035
{H}:  sup = 0.3050847457627119
{K}:  sup = 0.22033898305084745
{B}:  sup = 0.423728813559322
{G}:  sup = 0.6101694915254238
{J}:  sup = 0.11864406779661017
{L}:  sup = 0.6610169491525424
{E}:  sup = 0.3050847457627119
{F}:  sup = 0.4576271186440678
{C}:  sup = 0.4576271186440678
{I}:  sup = 0.0847457627118644

In [18]:
def apriori(dataset, min_support=0.5, VERBOSE=False):
    """Implements the Apriori algorithm.

    The Apriori algorithm will iteratively generate new candidate 
    k-itemsets using the frequent (k-1)-itemsets found in the previous 
    iteration.

    Parameters
    ----------
    dataset : list
        The dataset (a list of transactions) from which to generate candidate itemsets.

    min_support : float
        The minimum support threshold. Defaults to 0.5.

    Returns
    -------
    F : list
        The list of frequent itemsets.

    support_data : dict
        The support data for all candidate itemsets.


    """
    C1 = create_candidates(dataset)
    D = list(map(set, dataset))
    F1, support_data = support_prune(D, C1, min_support, VERBOSE=False) # prune candidate 1-itemsets
    F = [F1] # list of frequent itemsets; initialized to frequent 1-itemsets
    k = 2 # the itemset cardinality
    while (len(F[k - 2]) > 0):
        Ck = apriori_gen(F[k-2], k) # generate candidate itemsets
        Fk, supK = support_prune(D, Ck, min_support) # prune candidate itemsets
        support_data.update(supK) # update the support counts to reflect pruning
        F.append(Fk) # add the pruned candidate itemsets to the list of frequent itemsets
        k += 1

    if VERBOSE:
        # Print a list of all the frequent itemsets.
        for kset in F:
            for item in kset:
                print( "" \
                    + "{" \
                    + "".join(str(i) + ", " for i in iter(item)).rstrip(', ') \
                    + "}" \
                    + ":  sup = " + str(round(support_data[item], 3)))

    return F, support_data

In [19]:
def apriori_gen(freq_sets, k):
    """Generates candidate itemsets (via the F_k-1 x F_k-1 method).

    This operation generates new candidate k-itemsets based on the frequent 
    (k-1)-itemsets found in the previous iteration. The candidate generation 
    procedure merges a pair of frequent (k-1)-itemsets only if their first k-2 
    items are identical.

    Parameters
    ----------
    freq_sets : list
        The list of frequent (k-1)-itemsets.

    k : integer
        The cardinality of the current itemsets begin evaluated.

    Returns
    -------
    retlist : list
        The list of merged frequent itemsets.
    """
    retList = [] # list of merged frequent itemsets
    lenLk = len(freq_sets) # number of frequent itemsets
    for i in range(lenLk):
        for j in range(i+1, lenLk):
            a=list(freq_sets[i])
            b=list(freq_sets[j])
            a.sort()
            b.sort()
            F1 = a[:k-2] # first k-2 items of freq_sets[i]
            F2 = b[:k-2] # first k-2 items of freq_sets[j]

            if F1 == F2: # if the first k-2 items are identical
                # Merge the frequent itemsets.
                retList.append(freq_sets[i] | freq_sets[j])

    return retList

In [20]:
# Generate all the frequent itemsets using the Apriori algorithm.
F, support_data = apriori(dataset, min_support=0.02, VERBOSE=True)

{I}:  sup = 0.085
{C}:  sup = 0.458
{F}:  sup = 0.458
{E}:  sup = 0.305
{L}:  sup = 0.661
{J}:  sup = 0.119
{G}:  sup = 0.61
{B}:  sup = 0.424
{K}:  sup = 0.22
{H}:  sup = 0.305
{D}:  sup = 0.237
{A}:  sup = 0.119
{I, K}:  sup = 0.034
{E, I}:  sup = 0.034
{D, C}:  sup = 0.034
{L, I}:  sup = 0.051
{F, I}:  sup = 0.034
{C, I}:  sup = 0.085
{H, C}:  sup = 0.119
{F, H}:  sup = 0.153
{C, K}:  sup = 0.051
{C, E}:  sup = 0.102
{L, F}:  sup = 0.407
{G, C}:  sup = 0.254
{L, C}:  sup = 0.39
{F, C}:  sup = 0.322
{F, B}:  sup = 0.119
{F, G}:  sup = 0.271
{F, J}:  sup = 0.034
{L, H}:  sup = 0.271
{L, B}:  sup = 0.22
{H, E}:  sup = 0.102
{L, E}:  sup = 0.186
{B, J}:  sup = 0.068
{G, K}:  sup = 0.153
{G, B}:  sup = 0.271
{E, K}:  sup = 0.102
{E, B}:  sup = 0.203
{G, E}:  sup = 0.169
{L, A}:  sup = 0.051
{L, D}:  sup = 0.068
{L, G}:  sup = 0.339
{A, G}:  sup = 0.085
{D, G}:  sup = 0.169
{A, J}:  sup = 0.034
{D, J}:  sup = 0.068
{G, J}:  sup = 0.119
{D, B}:  sup = 0.102
{H, B}:  sup = 0.153
{B, K}:  sup = 0.136
{D, A}:  sup = 0.102
{A, H}:  sup = 0.034
{D, H}:  sup = 0.051
{A, K}:  sup = 0.034
{D, K}:  sup = 0.102
{H, K}:  sup = 0.034
{C, I, K}:  sup = 0.034
{C, E, I}:  sup = 0.034
{L, D, C}:  sup = 0.034
{H, C, F}:  sup = 0.068
{F, C, I}:  sup = 0.034
{L, C, I}:  sup = 0.051
{L, H, C}:  sup = 0.119
{H, C, E}:  sup = 0.034
{F, B, H}:  sup = 0.068
{L, F, H}:  sup = 0.153
{C, E, K}:  sup = 0.034
{L, F, B}:  sup = 0.102
{L, G, B}:  sup = 0.085
{L, G, E}:  sup = 0.068
{L, C, E}:  sup = 0.068
{G, C, E}:  sup = 0.034
{L, F, C}:  sup = 0.288
{G, C, F}:  sup = 0.22
{L, G, C}:  sup = 0.22
{L, F, G}:  sup = 0.237
{F, G, J}:  sup = 0.034
{F, B, G}:  sup = 0.051
{H, E, B}:  sup = 0.068
{L, H, E}:  sup = 0.102
{L, H, B}:  sup = 0.136
{L, B, E}:  sup = 0.119
{D, B, J}:  sup = 0.034
{G, B, J}:  sup = 0.068
{D, G, K}:  sup = 0.068
{D, G, B}:  sup = 0.085
{E, B, K}:  sup = 0.068
{G, E, K}:  sup = 0.085
{G, B, K}:  sup = 0.119
{E, G, B}:  sup = 0.136
{L, D, G}:  sup = 0.034
{L, A, D}:  sup = 0.034
{L, A, G}:  sup = 0.034
{A, J, D}:  sup = 0.034
{D, G, J}:  sup = 0.068
{A, G, D}:  sup = 0.085
{A, G, J}:  sup = 0.034
{D, B, K}:  sup = 0.068
{D, H, K}:  sup = 0.034
{D, A, K}:  sup = 0.034
{C, L, F, H}:  sup = 0.068
{C, L, H, E}:  sup = 0.034
{H, L, F, B}:  sup = 0.068
{G, L, F, B}:  sup = 0.034
{G, L, B, E}:  sup = 0.051
{C, G, L, F}:  sup = 0.203
{B, L, H, E}:  sup = 0.068
{G, D, B, J}:  sup = 0.034
{G, D, B, K}:  sup = 0.051
{G, E, B, K}:  sup = 0.068
{G, L, A, D}:  sup = 0.034
{G, A, J, D}:  sup = 0.034

In [21]:
def rules_from_conseq(freq_set, H, support_data, rules, min_confidence=0.7):
    """Generates a set of candidate rules.

    Parameters
    ----------
    freq_set : frozenset
        The complete list of frequent itemsets.

    H : list
        A list of frequent itemsets (of a particular length).

    support_data : dict
        The support data for all candidate itemsets.

    rules : list
        A potentially incomplete set of candidate rules above the minimum 
        confidence threshold.

    min_confidence : float
        The minimum confidence threshold. Defaults to 0.7.
    """
    m = len(H[0])
    if (len(freq_set) > (m+1)):
        Hmp1 = apriori_gen(H, m+1) # generate candidate itemsets
        Hmp1 = calc_confidence(freq_set, Hmp1,  support_data, rules, min_confidence)
        if len(Hmp1) > 1:
            # If there are candidate rules above the minimum confidence 
            # threshold, recurse on the list of these candidate rules.
            rules_from_conseq(freq_set, Hmp1, support_data, rules, min_confidence)

def calc_confidence(freq_set, H, support_data, rules, min_confidence=0.7, VERBOSE=False):
    """Evaluates the generated rules.

    One measurement for quantifying the goodness of association rules is 
    confidence. The confidence for a rule 'P implies H' (P -> H) is defined as 
    the support for P and H divided by the support for P 
    (support (P|H) / support(P)), where the | symbol denotes the set union 
    (thus P|H means all the items in set P or in set H).

    To calculate the confidence, we iterate through the frequent itemsets and 
    associated support data. For each frequent itemset, we divide the support 
    of the itemset by the support of the antecedent (left-hand-side of the 
    rule).

    Parameters
    ----------
    freq_set : frozenset
        The complete list of frequent itemsets.

    H : list
        A frequent itemset.

    min_support : float
        The minimum support threshold.

    rules : list
        A potentially incomplete set of candidate rules above the minimum 
        confidence threshold.

    min_confidence : float
        The minimum confidence threshold. Defaults to 0.7.

    Returns
    -------
    pruned_H : list
        The list of candidate rules above the minimum confidence threshold.
    """
    pruned_H = [] # list of candidate rules above the minimum confidence threshold
    for conseq in H: # iterate over the frequent itemsets
        conf = support_data[freq_set] / support_data[freq_set - conseq]
        if conf >= min_confidence:

            rules.append((freq_set - conseq, conseq, conf))
            pruned_H.append(conseq)

            if VERBOSE:
                print( "" \
                    + "{" \
                    + "".join([str(i) + ", " for i in iter(freq_set-conseq)]).rstrip(', ') \
                    + "}" \
                    + " ---> " \
                    + "{" \
                    + "".join([str(i) + ", " for i in iter(conseq)]).rstrip(', ') \
                    + "}" \
                    + ":  conf = " + str(round(conf, 3)) \
                    + ", sup = " + str(round(support_data[freq_set], 3)))

    return pruned_H

def generate_rules(F, support_data, min_confidence, VERBOSE=False):
    """Generates a set of candidate rules from a list of frequent itemsets.

    For each frequent itemset, we calculate the confidence of using a
    particular item as the rule consequent (right-hand-side of the rule). By 
    testing and merging the remaining rules, we recursively create a list of 
    pruned rules.

    Parameters
    ----------
    F : list
        A list of frequent itemsets.

    support_data : dict
        The corresponding support data for the frequent itemsets (L).

    min_confidence : float
        The minimum confidence threshold. Defaults to 0.7.

    Returns
    -------
    rules : list
        The list of candidate rules above the minimum confidence threshold.
    """
    rules = []
    for i in range(1, len(F)):
        for freq_set in F[i]:
            H1 = [frozenset([item]) for item in freq_set]

            if (i > 1):
                rules_from_conseq(freq_set, H1, support_data, rules, min_confidence)
            else:
                calc_confidence(freq_set, H1, support_data, rules, min_confidence, VERBOSE=VERBOSE)

    return rules

In [23]:
# Generate the association rules from a list of frequent itemsets.
H = generate_rules(F, support_data, min_confidence=0.01, VERBOSE=True)

{K} ---> {I}:  conf = 0.154, sup = 0.034
{I} ---> {K}:  conf = 0.4, sup = 0.034
{I} ---> {E}:  conf = 0.4, sup = 0.034
{E} ---> {I}:  conf = 0.111, sup = 0.034
{C} ---> {D}:  conf = 0.074, sup = 0.034
{D} ---> {C}:  conf = 0.143, sup = 0.034
{I} ---> {L}:  conf = 0.6, sup = 0.051
{L} ---> {I}:  conf = 0.077, sup = 0.051
{I} ---> {F}:  conf = 0.4, sup = 0.034
{F} ---> {I}:  conf = 0.074, sup = 0.034
{I} ---> {C}:  conf = 1.0, sup = 0.085
{C} ---> {I}:  conf = 0.185, sup = 0.085
{C} ---> {H}:  conf = 0.259, sup = 0.119
{H} ---> {C}:  conf = 0.389, sup = 0.119
{H} ---> {F}:  conf = 0.5, sup = 0.153
{F} ---> {H}:  conf = 0.333, sup = 0.153
{K} ---> {C}:  conf = 0.231, sup = 0.051
{C} ---> {K}:  conf = 0.111, sup = 0.051
{E} ---> {C}:  conf = 0.333, sup = 0.102
{C} ---> {E}:  conf = 0.222, sup = 0.102
{F} ---> {L}:  conf = 0.889, sup = 0.407
{L} ---> {F}:  conf = 0.615, sup = 0.407
{C} ---> {G}:  conf = 0.556, sup = 0.254
{G} ---> {C}:  conf = 0.417, sup = 0.254
{C} ---> {L}:  conf = 0.852, sup = 0.39
{L} ---> {C}:  conf = 0.59, sup = 0.39
{C} ---> {F}:  conf = 0.704, sup = 0.322
{F} ---> {C}:  conf = 0.704, sup = 0.322
{B} ---> {F}:  conf = 0.28, sup = 0.119
{F} ---> {B}:  conf = 0.259, sup = 0.119
{G} ---> {F}:  conf = 0.444, sup = 0.271
{F} ---> {G}:  conf = 0.593, sup = 0.271
{J} ---> {F}:  conf = 0.286, sup = 0.034
{F} ---> {J}:  conf = 0.074, sup = 0.034
{H} ---> {L}:  conf = 0.889, sup = 0.271
{L} ---> {H}:  conf = 0.41, sup = 0.271
{B} ---> {L}:  conf = 0.52, sup = 0.22
{L} ---> {B}:  conf = 0.333, sup = 0.22
{E} ---> {H}:  conf = 0.333, sup = 0.102
{H} ---> {E}:  conf = 0.333, sup = 0.102
{E} ---> {L}:  conf = 0.611, sup = 0.186
{L} ---> {E}:  conf = 0.282, sup = 0.186
{J} ---> {B}:  conf = 0.571, sup = 0.068
{B} ---> {J}:  conf = 0.16, sup = 0.068
{K} ---> {G}:  conf = 0.692, sup = 0.153
{G} ---> {K}:  conf = 0.25, sup = 0.153
{B} ---> {G}:  conf = 0.64, sup = 0.271
{G} ---> {B}:  conf = 0.444, sup = 0.271
{K} ---> {E}:  conf = 0.462, sup = 0.102
{E} ---> {K}:  conf = 0.333, sup = 0.102
{B} ---> {E}:  conf = 0.48, sup = 0.203
{E} ---> {B}:  conf = 0.667, sup = 0.203
{E} ---> {G}:  conf = 0.556, sup = 0.169
{G} ---> {E}:  conf = 0.278, sup = 0.169
{A} ---> {L}:  conf = 0.429, sup = 0.051
{L} ---> {A}:  conf = 0.077, sup = 0.051
{D} ---> {L}:  conf = 0.286, sup = 0.068
{L} ---> {D}:  conf = 0.103, sup = 0.068
{G} ---> {L}:  conf = 0.556, sup = 0.339
{L} ---> {G}:  conf = 0.513, sup = 0.339
{G} ---> {A}:  conf = 0.139, sup = 0.085
{A} ---> {G}:  conf = 0.714, sup = 0.085
{G} ---> {D}:  conf = 0.278, sup = 0.169
{D} ---> {G}:  conf = 0.714, sup = 0.169
{J} ---> {A}:  conf = 0.286, sup = 0.034
{A} ---> {J}:  conf = 0.286, sup = 0.034
{J} ---> {D}:  conf = 0.571, sup = 0.068
{D} ---> {J}:  conf = 0.286, sup = 0.068
{J} ---> {G}:  conf = 1.0, sup = 0.119
{G} ---> {J}:  conf = 0.194, sup = 0.119
{B} ---> {D}:  conf = 0.24, sup = 0.102
{D} ---> {B}:  conf = 0.429, sup = 0.102
{B} ---> {H}:  conf = 0.36, sup = 0.153
{H} ---> {B}:  conf = 0.5, sup = 0.153
{K} ---> {B}:  conf = 0.615, sup = 0.136
{B} ---> {K}:  conf = 0.32, sup = 0.136
{A} ---> {D}:  conf = 0.857, sup = 0.102
{D} ---> {A}:  conf = 0.429, sup = 0.102
{H} ---> {A}:  conf = 0.111, sup = 0.034
{A} ---> {H}:  conf = 0.286, sup = 0.034
{H} ---> {D}:  conf = 0.167, sup = 0.051
{D} ---> {H}:  conf = 0.214, sup = 0.051
{K} ---> {A}:  conf = 0.154, sup = 0.034
{A} ---> {K}:  conf = 0.286, sup = 0.034
{K} ---> {D}:  conf = 0.462, sup = 0.102
{D} ---> {K}:  conf = 0.429, sup = 0.102
{K} ---> {H}:  conf = 0.154, sup = 0.034
{H} ---> {K}:  conf = 0.111, sup = 0.034

340